version: '3.6'
services:
  ui:
    depends_on:
      - app
    container_name: ui
    image: asoltys/coinos-ui
    ports:
      - '8085:8085'
    environment:
      NODE_ENV: development
    volumes:
      - ../coinos-ui:/coinos
