version: '3.6'
services:
  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    restart: unless-stopped
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  ui:
    depends_on:
      - app
    container_name: ui
    image: asoltys/coinos-ui
    ports:
      - '8085:8085'
    environment:
      NODE_ENV: development
    volumes:
      - ../coinos-ui:/coinos
  app:
    depends_on:
      - maria
    container_name: app
    image: asoltys/coinos-server
    ports:
      - '3119:3119'
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
  bitcoin:
    image: asoltys/bitcoin:latest
    container_name: bitcoin
    ports:
      - ${BITCOIN_PEER_PORT}:18442
      - ${BITCOIN_NODE_PORT}:18443
    volumes:
      - ./config/bitcoin:/config
    restart: unless-stopped
  liquid:
    image: asoltys/liquid:latest
    container_name: liquid
    ports:
      - ${LIQUID_NODE_PORT}:18884
      - ${LIQUID_PEER_PORT}:18886
      - ${LIQUID_BLOCK_PORT}:18602
      - ${LIQUID_TX_PORT}:18603
    volumes:
      - ./config/liquid:/config
    restart: unless-stopped
  lightning:
    image: elementsproject/lightningd:latest
    container_name: lightning 
    environment:
      LIGHTNINGD_NETWORK: regtest
    volumes:
      - ./config/lightning:/root/.lightning
    restart: unless-stopped
  electrs-liquid:
    image: vulpemventures/electrs-liquid:latest
    container_name: electrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - liquid:18884
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    depends_on:
      - liquid
    ports:
      - ${LIQUID_ELECTRS_RPC_PORT}:60401
      - ${LIQUID_ELECTRS_PORT}:3002
    volumes:
      - ./liquidregtest/liquid-config/:/config
    restart: unless-stopped
  esplora-liquid:
    image: vulpemventures/esplora:latest
    container_name: esplora-liquid
    environment:
      API_URL: ${LIQUID_ELECTRS_URL}
      NATIVE_ASSET_ID: 5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225
      IS_ELEMENTS: 1
    ports:
      - ${LIQUID_ESPLORA_PORT}:5000
    restart: unless-stopped
  maria:
    container_name: mariadb
    image: mariadb:10.6.1
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3307:3306
