apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: la
  name: la
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: la
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: la
    spec:
      containers:
        - env:
            - name: LIGHTNINGD_NETWORK
              value: regtest
          image: elementsproject/lightningd:latest
          name: la
          resources: {}
          volumeMounts:
            - mountPath: /root/.lightning
              name: la-claim0
      restartPolicy: Always
      volumes:
        - name: la-claim0
          persistentVolumeClaim:
            claimName: la-claim0
status: {}
